baseURL = "https://clodman84.pages.dev/"
title = "Monkey Business"
theme = "PaperMod"
pagination.pagerSize = 5

enableRobotsTXT = true

[params]
  author = "clodman84"
  description = "A place to remember and show off the things I've done"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

[params.homeInfoParams]
  Title = "Monkey Business"
  Content = "A place to remember and show off the things I've done"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/clodman84"

[markup.highlight]
  noClasses = false

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[caches.images]
  dir = ':cacheDir/images'

[[menus.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 1

[[menus.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2
